# https://about.gitlab.com/2016/05/23/gitlab-container-registry/

stages:
- build
- test
- deploy

build_image:
  stage: build
  before_script:
    - docker info
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.local.net:4567
    - docker build -t gitlab.local.net:4567/testgroup/test-project .
    - docker push gitlab.local.net:4567/testgroup/test-project:latest

test_image:
  stage: test
  script:
    - docker info

deploy_job:
  stage: deploy
  variables:
    C_NAME: "dbapi"
    C_IMAGE: "gitlab.local.net:4567/testgroup/test-project:latest"
    C_APP_SETTINGS: "config.DevelopmentConfig"
    C_URL_PREFIX: ""
    C_PORT: "80"
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.local.net:4567
    - docker rm -f "${C_NAME}" || true
    - docker run --rm --name "${C_NAME}" -h '${C_NAME}.local.net' -v /dev/log:/dev/log -e APP_SETTINGS="${C_APP_SETTINGS}" -e  URL_PREFIX="${C_URL_PREFIX}" -e FLASK_PORT="${C_PORT}" -d ${C_IMG}
  when: manual
